// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnddwjkdfyzcqxrivayp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuZGR3amtkZnl6Y3F4cml2YXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMDA3MjAsImV4cCI6MjA1NTc3NjcyMH0.VHm7TkycYMmepPxNaTQ1cgQrC3GKB4Wnkp_SbstzpC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);